#pragma once

#include "../Default/framework.h"
#include <process.h>

namespace Client
{
	const unsigned int			g_iWinSizeX = 1280;
	const unsigned int			g_iWinSizeY = 720;

	enum class LEVEL { STATIC, LOADING, LOGO, OUTFITSELECT, TUTORIAL, KONOHA_VILLAGE, END };
	/*
	OBJECT ID? -> Abstract 계층이 아닌, 실제 구현되는 객체들만 가지게 될 ID.
	모든 객체는 고유한 ID를 가지게 된다.
	*/
	enum class OBJECTID {
		KONOHA_VILLAGE, TUTORIAL_MAP,
		PROPS, GATE, TREE,

		BACKGROUND, DUMMY, TERRAIN, OUTFIT_BACKGROUND,
		MANNEQUIN, PART_MANNEQUIN,


		PLAYER, PLAYER_HEAD, PLAYER_FACE, PLAYER_UPPER, PLAYER_LOWER, PLAYER_WEAPON,
		WHITEJETSU, BIRD, BOXER, PAJAMA, BOSS,

		EFFECT,

		TESTPANEL, TESTBUTTON,
		LOGO_PANEL, LOADING_PANEL, LOADINGBAR_PANEL, SKILLSLOT_PANEL,
		ATTACKTYPE_PANEL, MISSIONALERT_PANEL, COMBOKO_PANEL, OUTFITSELECT_PANEL, MODEL_PANEL,

		CREATECHARACTER_UI,
		SKILLSLOT_UI, DECIMAL_UI, TIMER_UI, TITLE_UI, KO_UI,
		PRESSANYBUTTON_UI, ROTATIONICON_UI, PROGRESSBAR_UI,
		MODELSELECTBUTTON_UI, MODELDECIDEBUTTON_UI, DIALOG_UI, WIN_UI, 
		CUTSCENE_UI, BOSSHP_UI,

		ENEMY_HPBAR, ICON,

		WOODHAND, RASENGAN, RASENSHURIKEN, KAMUI, FIREBALL, BIGSHARK, CHIDORI,

		KUNAI, ROPE, TRAIL,

		SKYBOX, 
		
		PARTICLE,
		SNOW, EXPLOSION,

		EFFECTOBJECT, EFFECTCONTAINER,

		NPC_KAKASHI,

		MONSTER_SPAWNER,

		TEST_CAMERA, OUTFITSELECT_CAMERA, MAIN_CAMERA, ACTION_CAEMRA, SKILL_ACTION_CAMERA, NPC_TALK_CAMERA, CUTSCENE_CAMERA,
		END
	};

	enum class SHADER_VTXPOSTEX_IDX {
		UI,
		UI_MASK,
		UI_ENEMYHPBAR,
		UI_PROGRESSBAR,
		UI_FADEINOUT,
		UI_SKILL,
		UI_SPECIALSKILL,
		OUTFIT_BACKGROUND,
		TRAIL, 
		FOOT_TRAIL,
		ROPE_TRAIL,
		END
	};

	/* OnCollision 이벤트가 발생하면 넘겨줄 콜리전 데스크. */

	/*
	필요한 값
	1. 맞춘 대상이 누구인가 -> 이건 콜리전 매니저의 아이디로 유추가능
	( PlayerAttack - Monster ) & ( MonsterAttack - Player )
	*/

	/*
	2. 어떤 처리를 해야하는가
	검 공격이라면 더 밀려나야 하고, 멀리 날아가는 모션이 있어야할 수도 있음.
	하지만 주먹 공격이라면 막타 제외하고 날아가는 모션이 안나온다.
	-> 같은 콜라이더여도 다르게 처리를 해줘야할 수 있음.
	-> 플레이어든 제츠든 COllision Desc 갖고 있게 하고, 콜라이더에 같이 묶어보내기?
	-> 플레이어는 HandAttack, 검 등 여러 콜리전이 존재함.
	-> 한번에 하나의 상태만을 보장하니까..
	-> 콜리전 데스크도 하나로 써도 될듯?

	-> 일단 기본적으로 몸통의 충돌처리를 할 콜라이더는
	Com_Collider로 이름을 고정하게 될 것.
	*/

	enum class COLLISION_TYPE {
		PLAYER, 
		MONSTER, 
		TRIGGER,
		END
	};

	enum class COLLIDER_HANDLE_ID {
		PLAYER_BODY,					// O
		PLAYER_HAND_ATTACK,				// O
		PLAYER_HAND_ATTACK_FINAL,		// O
		PLAYER_SWORD_ATTACK,			// O
		PLAYER_SWORD_ATTACK_FINAL,		// O

		PLAYER_NINJUTSU_RASENGAN,		// O
		PLAYER_NINJUTSU_RASENSHURIKEN,	// O
		PLAYER_NINJUTSU_RASENSHURIKEN_EXPLODE, // O
		PLAYER_NINJUTSU_RASENSHURIKEN_END, // O
		PLAYER_NINJUTSU_KAMUI,			// O
		PLAYER_NINJUTSU_KAMUI_END,		// O

		PLAYER_NINJUTSU_CHIDORI,
		PLAYER_NINJUTSU_FIREBALL,		// O
		PLAYER_NINJUTSU_BIGSHARK,		// O

		ENEMY_JETSU_ATTACK,				// O
		ENEMY_THROW,					// O

		ENEMY_JETSU_WOODHAND,			// O

		ENEMY_BOXER_ATTACK,
		ENEMY_BOXER_LEAFHURRICANE,
		ENEMY_BOXER_SPINKICK,

		ENEMY_PAJAMA_ATTACK,
		ENEMY_PAJAMA_FIREBALL,
		END
	};

	/* 일단은 튜토리얼과 관련된 로직만. */
	enum class TRIGGER_TYPE { 
		TUTORIAL_KAKASHI_TALK, TUTORIAL_SPAWNER_01, TUTORIAL_CLEAR, 
		KONOHA_VILLAGE_KAKASHI_TALK_1, 
		KONOHA_VILLAGE_SPAWNER_01, 
		KONOHA_VILLAGE_SPAWNER_01_CLEAR,
		KONOHA_VILLAGE_SPAWNER_02, 
		KONOHA_VILLAGE_SPAWNER_02_CLEAR,
		KONOHA_VILLAGE_SPAWNER_BOSS,
		KONOHA_VILLAGE_BOSS_CUTSCENE_END,
		/* 끝이 보인다.. */
		CLEAR,
		END };

	/* 모델 선택용 */
	enum class SELECT_TYPE { PARTS, HEAD, FACE, UPPER, ONE_CLOTH, LOWER, END };
}

using namespace Client;

extern HINSTANCE g_hInstance;
extern HWND g_hWnd;